# Generated by Django 2.2.7 on 2019-12-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
