# Generated by Django 2.2.7 on 2019-12-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0003_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='formModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
