# Generated by Django 2.2.7 on 2019-12-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='per',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]

