# Generated by Django 2.2.7 on 2019-12-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0002_student_per'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
            ],
        ),
    ]
