# Generated by Django 2.2.7 on 2019-12-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0003_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='eadd',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
